version: "3.9"
services:
  mysqldb:
    image: mysql
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=lifen
      - MYSQL_ROOT_PASSWORD=new_password

  app:
    build: .
    restart: on-failure
    depends_on:
      - mysqldb



volumes:
  db-data: